import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/layoutHome.module.css'
import Header from './components/Header'
import { Grid, Container, Row, Col, Button, IconButton} from 'rsuite'
import ArowBackIcon from '@rsuite/icons/ArowBack'
import EmailFillIcon from '@rsuite/icons/EmailFill'
import { ServicesBox } from './api/services'
import Link from 'next/link'
// Images 

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className={styles.main}>
        <div className={styles.x_section_one}>
          <Grid className='x_container'>
            <Container>
              <Row>
                <Col xs={24} md={10}>
                  <h1 className={styles.title}>
                    Đưa công việc 
                    kinh doanh 
                    lên internet
                  </h1>
                  <p className={styles.description}>
                    Thông qua dịch vụ thiết kế website và kho dữ liệu mẫu nội dung số để mở rộng kinh doanh trên internet hiệu quả.
                  </p>
                  <Button className={styles.x_black_button}>
                    <EmailFillIcon width={34} heigh={34}/>
                     ĐĂNG KÝ TƯ VẤN
                  </Button>
                </Col>
                <Col xs={24} md={14}>
                  <div className={styles.x_decoration_images}>
                    <div className={styles.x_decoation_1}>
                      <Image src="/layout/decoration_1.svg" width={175} height={762}/>
                    </div>
                    <div className={styles.x_decoation_0}>
                      <Image src="/layout/decoration_0.svg" width={220} height={266}/>
                    </div>
                    <Image src="/layout/layoutFrames.png" width={436} height={517}/>
                  </div>
                </Col>
              </Row>
            </Container>
          </Grid>
        </div>
        <hr className={styles.x_seperator} />
        <div className={styles.x_section_two}>
          <Grid className='x_container'>
            <Container>
              <Row>
                <Col xs={24}>
                  <h3 className={styles.x_title}>Công cụ Digital Content</h3>
                </Col>
                {
                  ServicesBox.map((val , index) => {
                      return(
                        <Col xs={24} md={8} key={index}>
                            <Link href={val.link}>
                              <a>
                                <div className={styles.x_services_box}>
                                    <span className={styles.x_service_icon}><Image src={val.image} width={58} height={58}/></span>
                                    <h4 className={styles.x_services_box_title}>{val.title}</h4>
                                    <p className={styles.x_services_box_content}>{val.content}</p>
                                </div>
                              </a>
                            </Link> 
                        </Col>
                      )
                  })
                }
              </Row>
            </Container>
          </Grid>
        </div>

        <div className={styles.x_section_three}>
          <Grid className='x_container'>
            <Container>
              <Row>
                <Col xs={24}>
                  <h3 className={styles.x_title_no_margin}>Sản phẩm & Dịch vụ cho bạn</h3>
                  <div style={{maxWidth: '640px', margin: 'auto'}}>
                  <p style={{textAlign: 'center', fontSize: '14px'}} className={styles.description}>Chúng tôi cung cấp các sản phẩm mẫu hỗ trợ các nội dung số để bạn có thể đưa thông tin doanh nghiệp và sản phẩm của mình lên mạng Internet một cách nhanh chóng và dễ dàng. Điều này giúp bạn gia tăng hiệu quả hoạt động với chi phí thấp nhất</p>
                  </div>
                </Col>
                <Col xs={12} className={styles.x_padding_cta}>
                    <div className={styles.x_creeper_box}>
                        <h4 className={styles.x_creeper_title}>Digital Content</h4>
                        <p className={styles.x_creeper_content}>Chúng tôi cung cấp các sản phẩm mẫu hỗ trợ các nội dung số để bạn có thể đưa thông tin doanh nghiệp và sản phẩm của mình lên mạng Internet một cách nhanh chóng và dễ dàng</p>
                    </div>
                </Col>

              </Row>
            </Container>
          </Grid>
        </div>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
